apiVersion: schema.confluent.m.crossplane.io/v1alpha1
kind: RegistryDek
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/registrydek
  labels:
    testing.upbound.io/example-name: my_dek
  name: my-dek
  namespace: crossplane-system
spec:
  forProvider:
    credentials:
    - keySecretRef:
        key: example-key
        name: example-secret
      secretSecretRef:
        key: example-key
        name: example-secret
    hardDelete: true
    kekNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    restEndpoint: ${data.confluent_schema_registry_cluster.essentials.rest_endpoint}
    schemaRegistryCluster:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: confluent_schema_registry_cluster
    subjectName: my_subject
