apiVersion: schema.confluent.m.crossplane.io/v1alpha1
kind: Tag
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/tag
  labels:
    testing.upbound.io/example-name: pii
  name: pii
  namespace: crossplane-system
spec:
  forProvider:
    credentials:
    - keySecretRef:
        key: example-key
        name: example-secret
      secretSecretRef:
        key: example-key
        name: example-secret
    description: PII tag
    name: PII
    restEndpoint: ${data.confluent_schema_registry_cluster.essentials.rest_endpoint}
    schemaRegistryCluster:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: confluent_schema_registry_cluster
