// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BusinessMetadataBindingCredentialsInitParameters struct {

	// The Schema Registry API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Schema Registry API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type BusinessMetadataBindingCredentialsObservation struct {
}

type BusinessMetadataBindingCredentialsParameters struct {

	// The Schema Registry API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Schema Registry API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type BusinessMetadataBindingInitParameters struct {

	// The block of key-value pair attributes.
	// The attributes.
	// +mapType=granular
	Attributes map[string]*string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// The name of the Business Metadata to be applied, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the business metadata to be applied.
	BusinessMetadataName *string `json:"businessMetadataName,omitempty" tf:"business_metadata_name,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	Credentials []BusinessMetadataBindingCredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The qualified name of the entity, for example, ${data.confluent_schema_registry_cluster.essentials.id}:.:${confluent_schema.purchase.schema_identifier}, ${data.confluent_schema_registry_cluster.essentials.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}. Refer to the Examples of qualified names to see the full list of supported values for the entity_name attribute.
	// The qualified name of the entity.
	EntityName *string `json:"entityName,omitempty" tf:"entity_name,omitempty"`

	// The entity type, for example, sr_schema. Refer to the Entity types to learn more about entity types.
	// The entity type.
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	SchemaRegistryCluster []BusinessMetadataBindingSchemaRegistryClusterInitParameters `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`
}

type BusinessMetadataBindingObservation struct {

	// The block of key-value pair attributes.
	// The attributes.
	// +mapType=granular
	Attributes map[string]*string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// The name of the Business Metadata to be applied, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the business metadata to be applied.
	BusinessMetadataName *string `json:"businessMetadataName,omitempty" tf:"business_metadata_name,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	Credentials []BusinessMetadataBindingCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The qualified name of the entity, for example, ${data.confluent_schema_registry_cluster.essentials.id}:.:${confluent_schema.purchase.schema_identifier}, ${data.confluent_schema_registry_cluster.essentials.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}. Refer to the Examples of qualified names to see the full list of supported values for the entity_name attribute.
	// The qualified name of the entity.
	EntityName *string `json:"entityName,omitempty" tf:"entity_name,omitempty"`

	// The entity type, for example, sr_schema. Refer to the Entity types to learn more about entity types.
	// The entity type.
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	SchemaRegistryCluster []BusinessMetadataBindingSchemaRegistryClusterObservation `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`
}

type BusinessMetadataBindingParameters struct {

	// The block of key-value pair attributes.
	// The attributes.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Attributes map[string]*string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// The name of the Business Metadata to be applied, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the business metadata to be applied.
	// +kubebuilder:validation:Optional
	BusinessMetadataName *string `json:"businessMetadataName,omitempty" tf:"business_metadata_name,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	// +kubebuilder:validation:Optional
	Credentials []BusinessMetadataBindingCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The qualified name of the entity, for example, ${data.confluent_schema_registry_cluster.essentials.id}:.:${confluent_schema.purchase.schema_identifier}, ${data.confluent_schema_registry_cluster.essentials.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}. Refer to the Examples of qualified names to see the full list of supported values for the entity_name attribute.
	// The qualified name of the entity.
	// +kubebuilder:validation:Optional
	EntityName *string `json:"entityName,omitempty" tf:"entity_name,omitempty"`

	// The entity type, for example, sr_schema. Refer to the Entity types to learn more about entity types.
	// The entity type.
	// +kubebuilder:validation:Optional
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	// +kubebuilder:validation:Optional
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	SchemaRegistryCluster []BusinessMetadataBindingSchemaRegistryClusterParameters `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`
}

type BusinessMetadataBindingSchemaRegistryClusterInitParameters struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type BusinessMetadataBindingSchemaRegistryClusterObservation struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type BusinessMetadataBindingSchemaRegistryClusterParameters struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

// BusinessMetadataBindingSpec defines the desired state of BusinessMetadataBinding
type BusinessMetadataBindingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BusinessMetadataBindingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BusinessMetadataBindingInitParameters `json:"initProvider,omitempty"`
}

// BusinessMetadataBindingStatus defines the observed state of BusinessMetadataBinding.
type BusinessMetadataBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BusinessMetadataBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BusinessMetadataBinding is the Schema for the BusinessMetadataBindings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,confluent}
type BusinessMetadataBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.businessMetadataName) || (has(self.initProvider) && has(self.initProvider.businessMetadataName))",message="spec.forProvider.businessMetadataName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entityName) || (has(self.initProvider) && has(self.initProvider.entityName))",message="spec.forProvider.entityName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entityType) || (has(self.initProvider) && has(self.initProvider.entityType))",message="spec.forProvider.entityType is a required parameter"
	Spec   BusinessMetadataBindingSpec   `json:"spec"`
	Status BusinessMetadataBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BusinessMetadataBindingList contains a list of BusinessMetadataBindings
type BusinessMetadataBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BusinessMetadataBinding `json:"items"`
}

// Repository type metadata.
var (
	BusinessMetadataBinding_Kind             = "BusinessMetadataBinding"
	BusinessMetadataBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BusinessMetadataBinding_Kind}.String()
	BusinessMetadataBinding_KindAPIVersion   = BusinessMetadataBinding_Kind + "." + CRDGroupVersion.String()
	BusinessMetadataBinding_GroupVersionKind = CRDGroupVersion.WithKind(BusinessMetadataBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&BusinessMetadataBinding{}, &BusinessMetadataBindingList{})
}
