// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/michielvha/upjet-provider-confluent/apis/cluster/schema/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this BusinessMetadata.
func (mg *BusinessMetadata) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this BusinessMetadataBinding.
func (mg *BusinessMetadataBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this RegistryClusterConfig.
func (mg *RegistryClusterConfig) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this RegistryClusterMode.
func (mg *RegistryClusterMode) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this RegistryDek.
func (mg *RegistryDek) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KekName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KekNameRef,
		Selector:     mg.Spec.ForProvider.KekNameSelector,
		To: reference.To{
			List:    &v1alpha1.RegistryKekList{},
			Managed: &v1alpha1.RegistryKek{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KekName")
	}
	mg.Spec.ForProvider.KekName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KekNameRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KekName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.KekNameRef,
		Selector:     mg.Spec.InitProvider.KekNameSelector,
		To: reference.To{
			List:    &v1alpha1.RegistryKekList{},
			Managed: &v1alpha1.RegistryKek{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KekName")
	}
	mg.Spec.InitProvider.KekName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KekNameRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this RegistryKek.
func (mg *RegistryKek) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Schema.
func (mg *Schema) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this SubjectConfig.
func (mg *SubjectConfig) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this SubjectMode.
func (mg *SubjectMode) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Tag.
func (mg *Tag) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this TagBinding.
func (mg *TagBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SchemaRegistryCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.RegistryClusterList{},
				Managed: &v1alpha1.RegistryCluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID")
		}
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SchemaRegistryCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}
