// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RegistryKekCredentialsInitParameters struct {

	// The Schema Registry API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Schema Registry API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type RegistryKekCredentialsObservation struct {
}

type RegistryKekCredentialsParameters struct {

	// The Schema Registry API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Schema Registry API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type RegistryKekInitParameters struct {

	// supports the following:
	// The Cluster API Credentials.
	Credentials []RegistryKekCredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The optional description for the KEK.
	Doc *string `json:"doc,omitempty" tf:"doc,omitempty"`

	// The optional flag to control whether a kek should be soft or hard deleted. Defaults to false.
	// Controls whether a kek should be soft or hard deleted. Set it to `true` if you want to hard delete a schema registry kek on destroy. Defaults to `false` (soft delete). Defaults to `false`.
	HardDelete *bool `json:"hardDelete,omitempty" tf:"hard_delete,omitempty"`

	// The ID of the key from KMS.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The type of Key Management Service (KMS). The supported values include aws-kms, azure-kms, and gcp-kms. Additionally, custom KMS types are supported as well.
	KMSType *string `json:"kmsType,omitempty" tf:"kms_type,omitempty"`

	// The custom properties to set (for example, KeyUsage=ENCRYPT_DECRYPT, KeyState=Enabled):
	// +mapType=granular
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	SchemaRegistryCluster []RegistryKekSchemaRegistryClusterInitParameters `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`

	// The optional flag to control whether the DEK Registry has shared access to the KMS. Defaults to false.
	// Defaults to `false`.
	Shared *bool `json:"shared,omitempty" tf:"shared,omitempty"`
}

type RegistryKekObservation struct {

	// supports the following:
	// The Cluster API Credentials.
	Credentials []RegistryKekCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The optional description for the KEK.
	Doc *string `json:"doc,omitempty" tf:"doc,omitempty"`

	// The optional flag to control whether a kek should be soft or hard deleted. Defaults to false.
	// Controls whether a kek should be soft or hard deleted. Set it to `true` if you want to hard delete a schema registry kek on destroy. Defaults to `false` (soft delete). Defaults to `false`.
	HardDelete *bool `json:"hardDelete,omitempty" tf:"hard_delete,omitempty"`

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the key from KMS.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The type of Key Management Service (KMS). The supported values include aws-kms, azure-kms, and gcp-kms. Additionally, custom KMS types are supported as well.
	KMSType *string `json:"kmsType,omitempty" tf:"kms_type,omitempty"`

	// The custom properties to set (for example, KeyUsage=ENCRYPT_DECRYPT, KeyState=Enabled):
	// +mapType=granular
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	SchemaRegistryCluster []RegistryKekSchemaRegistryClusterObservation `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`

	// The optional flag to control whether the DEK Registry has shared access to the KMS. Defaults to false.
	// Defaults to `false`.
	Shared *bool `json:"shared,omitempty" tf:"shared,omitempty"`
}

type RegistryKekParameters struct {

	// supports the following:
	// The Cluster API Credentials.
	// +kubebuilder:validation:Optional
	Credentials []RegistryKekCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The optional description for the KEK.
	// +kubebuilder:validation:Optional
	Doc *string `json:"doc,omitempty" tf:"doc,omitempty"`

	// The optional flag to control whether a kek should be soft or hard deleted. Defaults to false.
	// Controls whether a kek should be soft or hard deleted. Set it to `true` if you want to hard delete a schema registry kek on destroy. Defaults to `false` (soft delete). Defaults to `false`.
	// +kubebuilder:validation:Optional
	HardDelete *bool `json:"hardDelete,omitempty" tf:"hard_delete,omitempty"`

	// The ID of the key from KMS.
	// +kubebuilder:validation:Optional
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The type of Key Management Service (KMS). The supported values include aws-kms, azure-kms, and gcp-kms. Additionally, custom KMS types are supported as well.
	// +kubebuilder:validation:Optional
	KMSType *string `json:"kmsType,omitempty" tf:"kms_type,omitempty"`

	// The custom properties to set (for example, KeyUsage=ENCRYPT_DECRYPT, KeyState=Enabled):
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	// +kubebuilder:validation:Optional
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	SchemaRegistryCluster []RegistryKekSchemaRegistryClusterParameters `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`

	// The optional flag to control whether the DEK Registry has shared access to the KMS. Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	Shared *bool `json:"shared,omitempty" tf:"shared,omitempty"`
}

type RegistryKekSchemaRegistryClusterInitParameters struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	// +crossplane:generate:reference:type=github.com/michielvha/upjet-provider-confluent/apis/cluster/schema/v1alpha1.RegistryCluster
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a RegistryCluster in schema to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.NamespacedReference `json:"idRef,omitempty" tf:"-"`

	// Selector for a RegistryCluster in schema to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.NamespacedSelector `json:"idSelector,omitempty" tf:"-"`
}

type RegistryKekSchemaRegistryClusterObservation struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type RegistryKekSchemaRegistryClusterParameters struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	// +crossplane:generate:reference:type=github.com/michielvha/upjet-provider-confluent/apis/cluster/schema/v1alpha1.RegistryCluster
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a RegistryCluster in schema to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.NamespacedReference `json:"idRef,omitempty" tf:"-"`

	// Selector for a RegistryCluster in schema to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.NamespacedSelector `json:"idSelector,omitempty" tf:"-"`
}

// RegistryKekSpec defines the desired state of RegistryKek
type RegistryKekSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RegistryKekParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegistryKekInitParameters `json:"initProvider,omitempty"`
}

// RegistryKekStatus defines the observed state of RegistryKek.
type RegistryKekStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RegistryKekObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RegistryKek is the Schema for the RegistryKeks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,confluent}
type RegistryKek struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.kmsKeyId) || (has(self.initProvider) && has(self.initProvider.kmsKeyId))",message="spec.forProvider.kmsKeyId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.kmsType) || (has(self.initProvider) && has(self.initProvider.kmsType))",message="spec.forProvider.kmsType is a required parameter"
	Spec   RegistryKekSpec   `json:"spec"`
	Status RegistryKekStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegistryKekList contains a list of RegistryKeks
type RegistryKekList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RegistryKek `json:"items"`
}

// Repository type metadata.
var (
	RegistryKek_Kind             = "RegistryKek"
	RegistryKek_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RegistryKek_Kind}.String()
	RegistryKek_KindAPIVersion   = RegistryKek_Kind + "." + CRDGroupVersion.String()
	RegistryKek_GroupVersionKind = CRDGroupVersion.WithKind(RegistryKek_Kind)
)

func init() {
	SchemeBuilder.Register(&RegistryKek{}, &RegistryKekList{})
}
