// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TagBindingCredentialsInitParameters struct {

	// The Schema Registry API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Schema Registry API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type TagBindingCredentialsObservation struct {
}

type TagBindingCredentialsParameters struct {

	// The Schema Registry API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Schema Registry API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type TagBindingInitParameters struct {

	// supports the following:
	// The Cluster API Credentials.
	Credentials []TagBindingCredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// An optional flag to disable wait-for-readiness on create. Must be unset when importing. Defaults to false.
	// Defaults to `false`.
	DisableWaitForReady *bool `json:"disableWaitForReady,omitempty" tf:"disable_wait_for_ready,omitempty"`

	// The qualified name of the entity, for example, ${data.confluent_schema_registry_cluster.essentials.id}:.:${confluent_schema.purchase.schema_identifier}, ${data.confluent_schema_registry_cluster.essentials.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}. Refer to the Examples of qualified names to see the full list of supported values for the entity_name attribute.
	// The qualified name of the entity.
	EntityName *string `json:"entityName,omitempty" tf:"entity_name,omitempty"`

	// The entity type, for example, sr_schema. Refer to the Entity types to learn more about entity types.
	// The entity type.
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	SchemaRegistryCluster []TagBindingSchemaRegistryClusterInitParameters `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`

	// The name of the tag to be applied, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the tag to be applied.
	TagName *string `json:"tagName,omitempty" tf:"tag_name,omitempty"`
}

type TagBindingObservation struct {

	// supports the following:
	// The Cluster API Credentials.
	Credentials []TagBindingCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// An optional flag to disable wait-for-readiness on create. Must be unset when importing. Defaults to false.
	// Defaults to `false`.
	DisableWaitForReady *bool `json:"disableWaitForReady,omitempty" tf:"disable_wait_for_ready,omitempty"`

	// The qualified name of the entity, for example, ${data.confluent_schema_registry_cluster.essentials.id}:.:${confluent_schema.purchase.schema_identifier}, ${data.confluent_schema_registry_cluster.essentials.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}. Refer to the Examples of qualified names to see the full list of supported values for the entity_name attribute.
	// The qualified name of the entity.
	EntityName *string `json:"entityName,omitempty" tf:"entity_name,omitempty"`

	// The entity type, for example, sr_schema. Refer to the Entity types to learn more about entity types.
	// The entity type.
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	SchemaRegistryCluster []TagBindingSchemaRegistryClusterObservation `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`

	// The name of the tag to be applied, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the tag to be applied.
	TagName *string `json:"tagName,omitempty" tf:"tag_name,omitempty"`
}

type TagBindingParameters struct {

	// supports the following:
	// The Cluster API Credentials.
	// +kubebuilder:validation:Optional
	Credentials []TagBindingCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// An optional flag to disable wait-for-readiness on create. Must be unset when importing. Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	DisableWaitForReady *bool `json:"disableWaitForReady,omitempty" tf:"disable_wait_for_ready,omitempty"`

	// The qualified name of the entity, for example, ${data.confluent_schema_registry_cluster.essentials.id}:.:${confluent_schema.purchase.schema_identifier}, ${data.confluent_schema_registry_cluster.essentials.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}. Refer to the Examples of qualified names to see the full list of supported values for the entity_name attribute.
	// The qualified name of the entity.
	// +kubebuilder:validation:Optional
	EntityName *string `json:"entityName,omitempty" tf:"entity_name,omitempty"`

	// The entity type, for example, sr_schema. Refer to the Entity types to learn more about entity types.
	// The entity type.
	// +kubebuilder:validation:Optional
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	// +kubebuilder:validation:Optional
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	SchemaRegistryCluster []TagBindingSchemaRegistryClusterParameters `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`

	// The name of the tag to be applied, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the tag to be applied.
	// +kubebuilder:validation:Optional
	TagName *string `json:"tagName,omitempty" tf:"tag_name,omitempty"`
}

type TagBindingSchemaRegistryClusterInitParameters struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TagBindingSchemaRegistryClusterObservation struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TagBindingSchemaRegistryClusterParameters struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

// TagBindingSpec defines the desired state of TagBinding
type TagBindingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TagBindingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TagBindingInitParameters `json:"initProvider,omitempty"`
}

// TagBindingStatus defines the observed state of TagBinding.
type TagBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TagBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TagBinding is the Schema for the TagBindings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,confluent}
type TagBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entityName) || (has(self.initProvider) && has(self.initProvider.entityName))",message="spec.forProvider.entityName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entityType) || (has(self.initProvider) && has(self.initProvider.entityType))",message="spec.forProvider.entityType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tagName) || (has(self.initProvider) && has(self.initProvider.tagName))",message="spec.forProvider.tagName is a required parameter"
	Spec   TagBindingSpec   `json:"spec"`
	Status TagBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TagBindingList contains a list of TagBindings
type TagBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TagBinding `json:"items"`
}

// Repository type metadata.
var (
	TagBinding_Kind             = "TagBinding"
	TagBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TagBinding_Kind}.String()
	TagBinding_KindAPIVersion   = TagBinding_Kind + "." + CRDGroupVersion.String()
	TagBinding_GroupVersionKind = CRDGroupVersion.WithKind(TagBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&TagBinding{}, &TagBindingList{})
}
