apiVersion: kafka.confluent.crossplane.io/v1alpha1
kind: MirrorTopic
metadata:
  annotations:
    meta.upbound.io/example-id: kafka/v1alpha1/mirrortopic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterLink:
    - linkNameSelector:
        matchLabels:
          testing.upbound.io/example-name: source-outbound
    kafkaCluster:
    - credentials:
      - keySecretRef:
          key: attribute.id
          name: example-api-key
          namespace: upbound-system
        secretSecretRef:
          key: attribute.secret
          name: example-api-key
          namespace: upbound-system
      id: ${data.confluent_kafka_cluster.destination.id}
      restEndpoint: ${data.confluent_kafka_cluster.destination.rest_endpoint}
    sourceKafkaTopic:
    - topicName: orders
