// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AwsInitParameters struct {

	// The Amazon Resource Name (ARN) of the Resource Access Manager (RAM) Resource Share of the transit gateway your Confluent Cloud network attaches to.
	// The Amazon Resource Name (ARN) of the Resource Access Manager (RAM) Resource Share of the transit gateway your Confluent Cloud network attaches to.
	RAMResourceShareArn *string `json:"ramResourceShareArn,omitempty" tf:"ram_resource_share_arn,omitempty"`

	// List of destination routes for traffic from Confluent VPC to customer VPC via Transit Gateway.
	// List of destination routes for traffic from Confluent VPC to customer VPC via Transit Gateway.
	Routes []*string `json:"routes,omitempty" tf:"routes,omitempty"`

	// The ID of the AWS Transit Gateway that you want Confluent CLoud to be attached to. Must start with tgw-.
	// The ID of the AWS Transit Gateway that your Confluent Cloud network attaches to.
	TransitGatewayID *string `json:"transitGatewayId,omitempty" tf:"transit_gateway_id,omitempty"`
}

type AwsObservation struct {

	// The Amazon Resource Name (ARN) of the Resource Access Manager (RAM) Resource Share of the transit gateway your Confluent Cloud network attaches to.
	// The Amazon Resource Name (ARN) of the Resource Access Manager (RAM) Resource Share of the transit gateway your Confluent Cloud network attaches to.
	RAMResourceShareArn *string `json:"ramResourceShareArn,omitempty" tf:"ram_resource_share_arn,omitempty"`

	// List of destination routes for traffic from Confluent VPC to customer VPC via Transit Gateway.
	// List of destination routes for traffic from Confluent VPC to customer VPC via Transit Gateway.
	Routes []*string `json:"routes,omitempty" tf:"routes,omitempty"`

	// The ID of the AWS Transit Gateway VPC Attachment that attaches Confluent VPC to Transit Gateway.
	// The ID of the AWS Transit Gateway VPC Attachment that attaches Confluent VPC to Transit Gateway.
	TransitGatewayAttachmentID *string `json:"transitGatewayAttachmentId,omitempty" tf:"transit_gateway_attachment_id,omitempty"`

	// The ID of the AWS Transit Gateway that you want Confluent CLoud to be attached to. Must start with tgw-.
	// The ID of the AWS Transit Gateway that your Confluent Cloud network attaches to.
	TransitGatewayID *string `json:"transitGatewayId,omitempty" tf:"transit_gateway_id,omitempty"`
}

type AwsParameters struct {

	// The Amazon Resource Name (ARN) of the Resource Access Manager (RAM) Resource Share of the transit gateway your Confluent Cloud network attaches to.
	// The Amazon Resource Name (ARN) of the Resource Access Manager (RAM) Resource Share of the transit gateway your Confluent Cloud network attaches to.
	// +kubebuilder:validation:Optional
	RAMResourceShareArn *string `json:"ramResourceShareArn" tf:"ram_resource_share_arn,omitempty"`

	// List of destination routes for traffic from Confluent VPC to customer VPC via Transit Gateway.
	// List of destination routes for traffic from Confluent VPC to customer VPC via Transit Gateway.
	// +kubebuilder:validation:Optional
	Routes []*string `json:"routes" tf:"routes,omitempty"`

	// The ID of the AWS Transit Gateway that you want Confluent CLoud to be attached to. Must start with tgw-.
	// The ID of the AWS Transit Gateway that your Confluent Cloud network attaches to.
	// +kubebuilder:validation:Optional
	TransitGatewayID *string `json:"transitGatewayId" tf:"transit_gateway_id,omitempty"`
}

type EnvironmentInitParameters struct {

	// The ID of the Environment that the Transit Gateway Attachment belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EnvironmentObservation struct {

	// The ID of the Environment that the Transit Gateway Attachment belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EnvironmentParameters struct {

	// The ID of the Environment that the Transit Gateway Attachment belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type GatewayAttachmentInitParameters struct {

	// The AWS-specific Transit Gateway Attachment details. It supports the following:
	Aws []AwsInitParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// The name of the Transit Gateway Attachment.
	// The name of the Transit Gateway Attachment.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []EnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	Network []NetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`
}

type GatewayAttachmentObservation struct {

	// The AWS-specific Transit Gateway Attachment details. It supports the following:
	Aws []AwsObservation `json:"aws,omitempty" tf:"aws,omitempty"`

	// The name of the Transit Gateway Attachment.
	// The name of the Transit Gateway Attachment.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []EnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// The ID of the Environment that the Transit Gateway Attachment belongs to, for example, env-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	Network []NetworkObservation `json:"network,omitempty" tf:"network,omitempty"`
}

type GatewayAttachmentParameters struct {

	// The AWS-specific Transit Gateway Attachment details. It supports the following:
	// +kubebuilder:validation:Optional
	Aws []AwsParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// The name of the Transit Gateway Attachment.
	// The name of the Transit Gateway Attachment.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	// +kubebuilder:validation:Optional
	Environment []EnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	// +kubebuilder:validation:Optional
	Network []NetworkParameters `json:"network,omitempty" tf:"network,omitempty"`
}

type NetworkInitParameters struct {

	// The ID of the Environment that the Transit Gateway Attachment belongs to, for example, env-abc123.
	// The unique identifier for the network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworkObservation struct {

	// The ID of the Environment that the Transit Gateway Attachment belongs to, for example, env-abc123.
	// The unique identifier for the network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworkParameters struct {

	// The ID of the Environment that the Transit Gateway Attachment belongs to, for example, env-abc123.
	// The unique identifier for the network.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

// GatewayAttachmentSpec defines the desired state of GatewayAttachment
type GatewayAttachmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GatewayAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GatewayAttachmentInitParameters `json:"initProvider,omitempty"`
}

// GatewayAttachmentStatus defines the observed state of GatewayAttachment.
type GatewayAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GatewayAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GatewayAttachment is the Schema for the GatewayAttachments API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,confluent}
type GatewayAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	Spec   GatewayAttachmentSpec   `json:"spec"`
	Status GatewayAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GatewayAttachmentList contains a list of GatewayAttachments
type GatewayAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayAttachment `json:"items"`
}

// Repository type metadata.
var (
	GatewayAttachment_Kind             = "GatewayAttachment"
	GatewayAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GatewayAttachment_Kind}.String()
	GatewayAttachment_KindAPIVersion   = GatewayAttachment_Kind + "." + CRDGroupVersion.String()
	GatewayAttachment_GroupVersionKind = CRDGroupVersion.WithKind(GatewayAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&GatewayAttachment{}, &GatewayAttachmentList{})
}
