apiVersion: ksql.confluent.m.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: ksql/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    credentialIdentity:
    - id: ${confluent_service_account.app-ksql.id}
    csu: 1
    displayName: example
    environment:
    - id: ${confluent_environment.development.id}
    kafkaCluster:
    - id: ${confluent_kafka_cluster.basic.id}

---

apiVersion: environment.confluent.m.crossplane.io/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: ksql/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: development
  name: development
  namespace: crossplane-system
spec:
  forProvider:
    displayName: Development

---

apiVersion: kafka.confluent.m.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: ksql/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: crossplane-system
spec:
  forProvider:
    availability: SINGLE_ZONE
    basic:
    - {}
    cloud: AWS
    displayName: basic_kafka_cluster
    environment:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: development
    region: us-east-1

---

apiVersion: iam.confluent.m.crossplane.io/v1alpha1
kind: RoleBinding
metadata:
  annotations:
    meta.upbound.io/example-id: ksql/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: app-ksql-kafka-cluster-admin
  name: app-ksql-kafka-cluster-admin
  namespace: crossplane-system
spec:
  forProvider:
    crnPattern: ${confluent_kafka_cluster.basic.rbac_crn}
    principalSelector:
      matchLabels:
        testing.upbound.io/example-name: app-ksql
    roleName: CloudClusterAdmin

---

apiVersion: iam.confluent.m.crossplane.io/v1alpha1
kind: RoleBinding
metadata:
  annotations:
    meta.upbound.io/example-id: ksql/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: app-ksql-schema-registry-resource-owner
  name: app-ksql-schema-registry-resource-owner
  namespace: crossplane-system
spec:
  forProvider:
    crnPattern: ${format("%s/%s", data.confluent_schema_registry_cluster.essentials.resource_name,
      "subject=*")}
    principalSelector:
      matchLabels:
        testing.upbound.io/example-name: app-ksql
    roleName: ResourceOwner

---

apiVersion: iam.confluent.m.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: ksql/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: app-ksql
  name: app-ksql
  namespace: crossplane-system
spec:
  forProvider:
    description: Service account to manage 'example' ksqlDB cluster
    displayName: app-ksql
