// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CreatorInitParameters struct {
}

type CreatorObservation struct {

	// The ID of the Invitation, for example, i-zyw30.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type CreatorParameters struct {
}

type InvitationInitParameters struct {

	// Defaults to false. See issue #263 for more context.
	// Defaults to `false`.
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// Accepted values are: AUTH_TYPE_LOCAL and AUTH_TYPE_SSO. The user/invitee's authentication type. Note that only the OrganizationAdmin role can invite AUTH_TYPE_LOCAL users to SSO organizations. The user's auth_type is set as AUTH_TYPE_SSO by default if the organization has SSO enabled. Otherwise, the user's auth_type is AUTH_TYPE_LOCAL by default.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// The user/invitee's email address.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type InvitationObservation struct {

	// The timestamp that the invitation was accepted.
	AcceptedAt *string `json:"acceptedAt,omitempty" tf:"accepted_at,omitempty"`

	// Defaults to false. See issue #263 for more context.
	// Defaults to `false`.
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// Accepted values are: AUTH_TYPE_LOCAL and AUTH_TYPE_SSO. The user/invitee's authentication type. Note that only the OrganizationAdmin role can invite AUTH_TYPE_LOCAL users to SSO organizations. The user's auth_type is set as AUTH_TYPE_SSO by default if the organization has SSO enabled. Otherwise, the user's auth_type is AUTH_TYPE_LOCAL by default.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// supports the following:
	Creator []CreatorObservation `json:"creator,omitempty" tf:"creator,omitempty"`

	// The user/invitee's email address.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The timestamp that the invitation will expire.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// The ID of the Invitation, for example, i-zyw30.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The status of invitations. Accepted values are: INVITE_STATUS_SENT,INVITE_STATUS_STAGED,INVITE_STATUS_ACCEPTED,INVITE_STATUS_EXPIRED, and INVITE_STATUS_DEACTIVATED.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// supports the following:
	User []UserObservation `json:"user,omitempty" tf:"user,omitempty"`
}

type InvitationParameters struct {

	// Defaults to false. See issue #263 for more context.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// Accepted values are: AUTH_TYPE_LOCAL and AUTH_TYPE_SSO. The user/invitee's authentication type. Note that only the OrganizationAdmin role can invite AUTH_TYPE_LOCAL users to SSO organizations. The user's auth_type is set as AUTH_TYPE_SSO by default if the organization has SSO enabled. Otherwise, the user's auth_type is AUTH_TYPE_LOCAL by default.
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// The user/invitee's email address.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type UserInitParameters struct {
}

type UserObservation struct {

	// The ID of the Invitation, for example, i-zyw30.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type UserParameters struct {
}

// InvitationSpec defines the desired state of Invitation
type InvitationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InvitationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InvitationInitParameters `json:"initProvider,omitempty"`
}

// InvitationStatus defines the observed state of Invitation.
type InvitationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InvitationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Invitation is the Schema for the Invitations API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,confluent}
type Invitation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	Spec   InvitationSpec   `json:"spec"`
	Status InvitationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InvitationList contains a list of Invitations
type InvitationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Invitation `json:"items"`
}

// Repository type metadata.
var (
	Invitation_Kind             = "Invitation"
	Invitation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Invitation_Kind}.String()
	Invitation_KindAPIVersion   = Invitation_Kind + "." + CRDGroupVersion.String()
	Invitation_GroupVersionKind = CRDGroupVersion.WithKind(Invitation_Kind)
)

func init() {
	SchemeBuilder.Register(&Invitation{}, &InvitationList{})
}
