// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ClusterInitParameters struct {

	// supports the following:
	CredentialIdentity []CredentialIdentityInitParameters `json:"credentialIdentity,omitempty" tf:"credential_identity,omitempty"`

	// The number of Confluent Streaming Units (CSUs) for the ksqlDB cluster.
	// The number of Confluent Streaming Units (CSUs) for the ksqlDB cluster.
	Csu *float64 `json:"csu,omitempty" tf:"csu,omitempty"`

	// The name of the ksqlDB cluster.
	// The name of the ksqlDB cluster.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []EnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	KafkaCluster []KafkaClusterInitParameters `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// Controls whether the row data should be included in the processing log topic. Set it to false if you don't want to emit sensitive information to the processing log. Defaults to true.
	// Controls whether the row data should be included in the processing log topic. Set it to `false` if you don't want to emit sensitive information to the processing log. Defaults to `true`. Defaults to `true`.
	UseDetailedProcessingLog *bool `json:"useDetailedProcessingLog,omitempty" tf:"use_detailed_processing_log,omitempty"`
}

type ClusterObservation struct {

	// An API Version of the schema version of the ksqlDB cluster, for example, ksqldbcm/v2.
	APIVersion *string `json:"apiVersion,omitempty" tf:"api_version,omitempty"`

	// supports the following:
	CredentialIdentity []CredentialIdentityObservation `json:"credentialIdentity,omitempty" tf:"credential_identity,omitempty"`

	// The number of Confluent Streaming Units (CSUs) for the ksqlDB cluster.
	// The number of Confluent Streaming Units (CSUs) for the ksqlDB cluster.
	Csu *float64 `json:"csu,omitempty" tf:"csu,omitempty"`

	// The name of the ksqlDB cluster.
	// The name of the ksqlDB cluster.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []EnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// The ID of the associated Environment, for example, env-xyz456.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// supports the following:
	KafkaCluster []KafkaClusterObservation `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// A kind of the ksqlDB cluster, for example, Cluster.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// The Confluent Resource Name of the ksqlDB cluster.
	// The Confluent Resource Name of the ksqlDB cluster.
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`

	// The API endpoint of the ksqlDB cluster, for example, https://pksqlc-00000.us-central1.gcp.glb.confluent.cloud.
	// The API endpoint of the ksqlDB cluster.
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// The amount of storage (in GB) provisioned to the ksqlDB cluster.
	// The amount of storage (in GB) provisioned to the ksqlDB cluster.
	Storage *float64 `json:"storage,omitempty" tf:"storage,omitempty"`

	// Topic name prefix used by this ksqlDB cluster. Used to assign ACLs for this ksqlDB cluster to use, for example, pksqlc-00000.
	// Topic name prefix used by this ksqlDB cluster. Used to assign ACLs for this ksqlDB cluster to use.
	TopicPrefix *string `json:"topicPrefix,omitempty" tf:"topic_prefix,omitempty"`

	// Controls whether the row data should be included in the processing log topic. Set it to false if you don't want to emit sensitive information to the processing log. Defaults to true.
	// Controls whether the row data should be included in the processing log topic. Set it to `false` if you don't want to emit sensitive information to the processing log. Defaults to `true`. Defaults to `true`.
	UseDetailedProcessingLog *bool `json:"useDetailedProcessingLog,omitempty" tf:"use_detailed_processing_log,omitempty"`
}

type ClusterParameters struct {

	// supports the following:
	// +kubebuilder:validation:Optional
	CredentialIdentity []CredentialIdentityParameters `json:"credentialIdentity,omitempty" tf:"credential_identity,omitempty"`

	// The number of Confluent Streaming Units (CSUs) for the ksqlDB cluster.
	// The number of Confluent Streaming Units (CSUs) for the ksqlDB cluster.
	// +kubebuilder:validation:Optional
	Csu *float64 `json:"csu,omitempty" tf:"csu,omitempty"`

	// The name of the ksqlDB cluster.
	// The name of the ksqlDB cluster.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	// +kubebuilder:validation:Optional
	Environment []EnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	KafkaCluster []KafkaClusterParameters `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// Controls whether the row data should be included in the processing log topic. Set it to false if you don't want to emit sensitive information to the processing log. Defaults to true.
	// Controls whether the row data should be included in the processing log topic. Set it to `false` if you don't want to emit sensitive information to the processing log. Defaults to `true`. Defaults to `true`.
	// +kubebuilder:validation:Optional
	UseDetailedProcessingLog *bool `json:"useDetailedProcessingLog,omitempty" tf:"use_detailed_processing_log,omitempty"`
}

type CredentialIdentityInitParameters struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The credential_identity to which this belongs. The credential_identity can be one of iam.v2.User, iam.v2.ServiceAccount.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type CredentialIdentityObservation struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The credential_identity to which this belongs. The credential_identity can be one of iam.v2.User, iam.v2.ServiceAccount.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type CredentialIdentityParameters struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The credential_identity to which this belongs. The credential_identity can be one of iam.v2.User, iam.v2.ServiceAccount.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type EnvironmentInitParameters struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EnvironmentObservation struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EnvironmentParameters struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The unique identifier for the environment.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type KafkaClusterInitParameters struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type KafkaClusterObservation struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type KafkaClusterParameters struct {

	// The ID of the associated Environment, for example, env-xyz456.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterInitParameters `json:"initProvider,omitempty"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cluster is the Schema for the Clusters API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.credentialIdentity) || (has(self.initProvider) && has(self.initProvider.credentialIdentity))",message="spec.forProvider.credentialIdentity is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.csu) || (has(self.initProvider) && has(self.initProvider.csu))",message="spec.forProvider.csu is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.kafkaCluster) || (has(self.initProvider) && has(self.initProvider.kafkaCluster))",message="spec.forProvider.kafkaCluster is a required parameter"
	Spec   ClusterSpec   `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Clusters
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

// Repository type metadata.
var (
	Cluster_Kind             = "Cluster"
	Cluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cluster_Kind}.String()
	Cluster_KindAPIVersion   = Cluster_Kind + "." + CRDGroupVersion.String()
	Cluster_GroupVersionKind = CRDGroupVersion.WithKind(Cluster_Kind)
)

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
