apiVersion: kafka.confluent.m.crossplane.io/v1alpha1
kind: ClusterConfig
metadata:
  annotations:
    meta.upbound.io/example-id: kafka/v1alpha1/clusterconfig
  labels:
    testing.upbound.io/example-name: orders
  name: orders
  namespace: crossplane-system
spec:
  forProvider:
    config:
      auto.create.topics.enable: "true"
      log.retention.ms: "604800123"
    credentials:
    - keySecretRef:
        key: attribute.id
        name: example-api-key
      secretSecretRef:
        key: attribute.secret
        name: example-api-key
    kafkaCluster:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: dedicated
    restEndpoint: ${confluent_kafka_cluster.dedicated.rest_endpoint}
