// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this APIKey.
func (mg *APIKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Owner); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Owner[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Owner[i3].IDRef,
			Selector:     mg.Spec.ForProvider.Owner[i3].IDSelector,
			To: reference.To{
				List:    &ServiceAccountList{},
				Managed: &ServiceAccount{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Owner[i3].ID")
		}
		mg.Spec.ForProvider.Owner[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Owner[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Owner); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Owner[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Owner[i3].IDRef,
			Selector:     mg.Spec.InitProvider.Owner[i3].IDSelector,
			To: reference.To{
				List:    &ServiceAccountList{},
				Managed: &ServiceAccount{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Owner[i3].ID")
		}
		mg.Spec.InitProvider.Owner[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Owner[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this IdentityPool.
func (mg *IdentityPool) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.IdentityProvider); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IdentityProvider[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.IdentityProvider[i3].IDRef,
			Selector:     mg.Spec.ForProvider.IdentityProvider[i3].IDSelector,
			To: reference.To{
				List:    &IdentityProviderList{},
				Managed: &IdentityProvider{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.IdentityProvider[i3].ID")
		}
		mg.Spec.ForProvider.IdentityProvider[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.IdentityProvider[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.IdentityProvider); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IdentityProvider[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.IdentityProvider[i3].IDRef,
			Selector:     mg.Spec.InitProvider.IdentityProvider[i3].IDSelector,
			To: reference.To{
				List:    &IdentityProviderList{},
				Managed: &IdentityProvider{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.IdentityProvider[i3].ID")
		}
		mg.Spec.InitProvider.IdentityProvider[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.IdentityProvider[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this RoleBinding.
func (mg *RoleBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Principal),
		Extract:      resource.ExtractParamPath("id", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PrincipalRef,
		Selector:     mg.Spec.ForProvider.PrincipalSelector,
		To: reference.To{
			List:    &ServiceAccountList{},
			Managed: &ServiceAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Principal")
	}
	mg.Spec.ForProvider.Principal = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PrincipalRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Principal),
		Extract:      resource.ExtractParamPath("id", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PrincipalRef,
		Selector:     mg.Spec.InitProvider.PrincipalSelector,
		To: reference.To{
			List:    &ServiceAccountList{},
			Managed: &ServiceAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Principal")
	}
	mg.Spec.InitProvider.Principal = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PrincipalRef = rsp.ResolvedReference

	return nil
}
