// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AttributeDefinitionInitParameters struct {

	// The default value of this attribute.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// The description of this attribute.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// An optional flag to control whether the attribute should be optional or required. The default value is false.
	IsOptional *bool `json:"isOptional,omitempty" tf:"is_optional,omitempty"`

	// The name of the Business Metadata, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AttributeDefinitionObservation struct {

	// The default value of this attribute.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// The description of this attribute.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// An optional flag to control whether the attribute should be optional or required. The default value is false.
	IsOptional *bool `json:"isOptional,omitempty" tf:"is_optional,omitempty"`

	// The name of the Business Metadata, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Block for the attribute options:
	// +mapType=granular
	Options map[string]*string `json:"options,omitempty" tf:"options,omitempty"`

	// The type of the attribute, it always returns string.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AttributeDefinitionParameters struct {

	// The default value of this attribute.
	// +kubebuilder:validation:Optional
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// The description of this attribute.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// An optional flag to control whether the attribute should be optional or required. The default value is false.
	// +kubebuilder:validation:Optional
	IsOptional *bool `json:"isOptional,omitempty" tf:"is_optional,omitempty"`

	// The name of the Business Metadata, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type BusinessMetadataInitParameters struct {

	// The list of attribute definitions (see Business Metadata for more details):
	AttributeDefinition []AttributeDefinitionInitParameters `json:"attributeDefinition,omitempty" tf:"attribute_definition,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	Credentials []CredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The description of this attribute.
	// The description of the Business Metadata to be created.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the Business Metadata, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the Business Metadata to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	SchemaRegistryCluster []SchemaRegistryClusterInitParameters `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`
}

type BusinessMetadataObservation struct {

	// The list of attribute definitions (see Business Metadata for more details):
	AttributeDefinition []AttributeDefinitionObservation `json:"attributeDefinition,omitempty" tf:"attribute_definition,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	Credentials []CredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The description of this attribute.
	// The description of the Business Metadata to be created.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the Business Metadata, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the Business Metadata to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	SchemaRegistryCluster []SchemaRegistryClusterObservation `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`

	// The version of the Business Metadata, for example, 1.
	// The version.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type BusinessMetadataParameters struct {

	// The list of attribute definitions (see Business Metadata for more details):
	// +kubebuilder:validation:Optional
	AttributeDefinition []AttributeDefinitionParameters `json:"attributeDefinition,omitempty" tf:"attribute_definition,omitempty"`

	// supports the following:
	// The Cluster API Credentials.
	// +kubebuilder:validation:Optional
	Credentials []CredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The description of this attribute.
	// The description of the Business Metadata to be created.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the Business Metadata, for example, PII. The name must not be empty and consist of a letter followed by a sequence of letter, number, space, or _ characters.
	// The name of the Business Metadata to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The REST endpoint of the Schema Registry cluster, for example, https://psrc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Schema Registry cluster, for example, `https://psrc-00000.us-central1.gcp.confluent.cloud:443`).
	// +kubebuilder:validation:Optional
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	SchemaRegistryCluster []SchemaRegistryClusterParameters `json:"schemaRegistryCluster,omitempty" tf:"schema_registry_cluster,omitempty"`
}

type CredentialsInitParameters struct {

	// The Schema Registry API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	KeySecretRef v1.SecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Schema Registry API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	SecretSecretRef v1.SecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type CredentialsObservation struct {
}

type CredentialsParameters struct {

	// The Schema Registry API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	KeySecretRef v1.SecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Schema Registry API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.SecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type SchemaRegistryClusterInitParameters struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SchemaRegistryClusterObservation struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SchemaRegistryClusterParameters struct {

	// The ID of the Schema Registry cluster, for example, lsrc-abc123.
	// The Schema Registry cluster ID (e.g., `lsrc-abc123`).
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

// BusinessMetadataSpec defines the desired state of BusinessMetadata
type BusinessMetadataSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BusinessMetadataParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BusinessMetadataInitParameters `json:"initProvider,omitempty"`
}

// BusinessMetadataStatus defines the observed state of BusinessMetadata.
type BusinessMetadataStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BusinessMetadataObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BusinessMetadata is the Schema for the BusinessMetadatas API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type BusinessMetadata struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   BusinessMetadataSpec   `json:"spec"`
	Status BusinessMetadataStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BusinessMetadataList contains a list of BusinessMetadatas
type BusinessMetadataList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BusinessMetadata `json:"items"`
}

// Repository type metadata.
var (
	BusinessMetadata_Kind             = "BusinessMetadata"
	BusinessMetadata_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BusinessMetadata_Kind}.String()
	BusinessMetadata_KindAPIVersion   = BusinessMetadata_Kind + "." + CRDGroupVersion.String()
	BusinessMetadata_GroupVersionKind = CRDGroupVersion.WithKind(BusinessMetadata_Kind)
)

func init() {
	SchemeBuilder.Register(&BusinessMetadata{}, &BusinessMetadataList{})
}
