// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this RegistryDek.
func (mg *RegistryDek) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KekName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KekNameRef,
		Selector:     mg.Spec.ForProvider.KekNameSelector,
		To: reference.To{
			List:    &RegistryKekList{},
			Managed: &RegistryKek{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KekName")
	}
	mg.Spec.ForProvider.KekName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KekNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KekName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.KekNameRef,
		Selector:     mg.Spec.InitProvider.KekNameSelector,
		To: reference.To{
			List:    &RegistryKekList{},
			Managed: &RegistryKek{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KekName")
	}
	mg.Spec.InitProvider.KekName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KekNameRef = rsp.ResolvedReference

	return nil
}
