// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PeeringAwsInitParameters struct {

	// The AWS Account ID of the peer VPC owner. You can find your AWS Account ID here under My Account section of the AWS Management Console. Must be a 12 character string.
	// AWS account for VPC to peer with the network.
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// The region of the AWS peer VPC.
	// Region of customer VPC.
	CustomerRegion *string `json:"customerRegion,omitempty" tf:"customer_region,omitempty"`

	// The AWS VPC CIDR blocks or subsets. This must be from the supported CIDR blocks and must not overlap with your Confluent Cloud CIDR block or any other network peering connection VPC CIDR (learn more about the requirements here). You can find AWS VPC CIDR here under Your VPCs -> Target VPC -> Details section of the AWS Management Console.
	// List of routes for the peering.
	Routes []*string `json:"routes,omitempty" tf:"routes,omitempty"`

	// The AWS VPC ID of the peer VPC that you're peering with Confluent Cloud. You can find your AWS VPC ID here under Your VPCs section of the AWS Management Console. Must start with vpc-.
	// The id of the AWS VPC to peer with.
	VPC *string `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type PeeringAwsObservation struct {

	// The AWS Account ID of the peer VPC owner. You can find your AWS Account ID here under My Account section of the AWS Management Console. Must be a 12 character string.
	// AWS account for VPC to peer with the network.
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// The region of the AWS peer VPC.
	// Region of customer VPC.
	CustomerRegion *string `json:"customerRegion,omitempty" tf:"customer_region,omitempty"`

	// The AWS VPC CIDR blocks or subsets. This must be from the supported CIDR blocks and must not overlap with your Confluent Cloud CIDR block or any other network peering connection VPC CIDR (learn more about the requirements here). You can find AWS VPC CIDR here under Your VPCs -> Target VPC -> Details section of the AWS Management Console.
	// List of routes for the peering.
	Routes []*string `json:"routes,omitempty" tf:"routes,omitempty"`

	// The AWS VPC ID of the peer VPC that you're peering with Confluent Cloud. You can find your AWS VPC ID here under Your VPCs section of the AWS Management Console. Must start with vpc-.
	// The id of the AWS VPC to peer with.
	VPC *string `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type PeeringAwsParameters struct {

	// The AWS Account ID of the peer VPC owner. You can find your AWS Account ID here under My Account section of the AWS Management Console. Must be a 12 character string.
	// AWS account for VPC to peer with the network.
	// +kubebuilder:validation:Optional
	Account *string `json:"account" tf:"account,omitempty"`

	// The region of the AWS peer VPC.
	// Region of customer VPC.
	// +kubebuilder:validation:Optional
	CustomerRegion *string `json:"customerRegion" tf:"customer_region,omitempty"`

	// The AWS VPC CIDR blocks or subsets. This must be from the supported CIDR blocks and must not overlap with your Confluent Cloud CIDR block or any other network peering connection VPC CIDR (learn more about the requirements here). You can find AWS VPC CIDR here under Your VPCs -> Target VPC -> Details section of the AWS Management Console.
	// List of routes for the peering.
	// +kubebuilder:validation:Optional
	Routes []*string `json:"routes" tf:"routes,omitempty"`

	// The AWS VPC ID of the peer VPC that you're peering with Confluent Cloud. You can find your AWS VPC ID here under Your VPCs section of the AWS Management Console. Must start with vpc-.
	// The id of the AWS VPC to peer with.
	// +kubebuilder:validation:Optional
	VPC *string `json:"vpc" tf:"vpc,omitempty"`
}

type PeeringAzureInitParameters struct {

	// The region of the AWS peer VPC.
	// Region of customer VNet.
	CustomerRegion *string `json:"customerRegion,omitempty" tf:"customer_region,omitempty"`

	// The Tenant ID that represents an organization in Azure Active Directory. You can find your Azure Tenant ID in the Azure Portal under Azure Active Directory. Must be a valid 32 character UUID string.
	// Customer Azure tenant.
	Tenant *string `json:"tenant,omitempty" tf:"tenant,omitempty"`

	// The resource (composite) ID of the peer Virtual Network that you're peering with Confluent Cloud, in the format /subscriptions/<Subscription ID>/resourceGroups/<Resource Group Name>/providers/Microsoft.Network/virtualNetworks/<VNet name>. You can find Subscription ID, Resource Group Name and your VNet name under Virtual Networks -> Target VNet -> Essentials section of your Microsoft Azure Portal.
	// Customer VNet to peer with.
	Vnet *string `json:"vnet,omitempty" tf:"vnet,omitempty"`
}

type PeeringAzureObservation struct {

	// The region of the AWS peer VPC.
	// Region of customer VNet.
	CustomerRegion *string `json:"customerRegion,omitempty" tf:"customer_region,omitempty"`

	// The Tenant ID that represents an organization in Azure Active Directory. You can find your Azure Tenant ID in the Azure Portal under Azure Active Directory. Must be a valid 32 character UUID string.
	// Customer Azure tenant.
	Tenant *string `json:"tenant,omitempty" tf:"tenant,omitempty"`

	// The resource (composite) ID of the peer Virtual Network that you're peering with Confluent Cloud, in the format /subscriptions/<Subscription ID>/resourceGroups/<Resource Group Name>/providers/Microsoft.Network/virtualNetworks/<VNet name>. You can find Subscription ID, Resource Group Name and your VNet name under Virtual Networks -> Target VNet -> Essentials section of your Microsoft Azure Portal.
	// Customer VNet to peer with.
	Vnet *string `json:"vnet,omitempty" tf:"vnet,omitempty"`
}

type PeeringAzureParameters struct {

	// The region of the AWS peer VPC.
	// Region of customer VNet.
	// +kubebuilder:validation:Optional
	CustomerRegion *string `json:"customerRegion" tf:"customer_region,omitempty"`

	// The Tenant ID that represents an organization in Azure Active Directory. You can find your Azure Tenant ID in the Azure Portal under Azure Active Directory. Must be a valid 32 character UUID string.
	// Customer Azure tenant.
	// +kubebuilder:validation:Optional
	Tenant *string `json:"tenant" tf:"tenant,omitempty"`

	// The resource (composite) ID of the peer Virtual Network that you're peering with Confluent Cloud, in the format /subscriptions/<Subscription ID>/resourceGroups/<Resource Group Name>/providers/Microsoft.Network/virtualNetworks/<VNet name>. You can find Subscription ID, Resource Group Name and your VNet name under Virtual Networks -> Target VNet -> Essentials section of your Microsoft Azure Portal.
	// Customer VNet to peer with.
	// +kubebuilder:validation:Optional
	Vnet *string `json:"vnet" tf:"vnet,omitempty"`
}

type PeeringEnvironmentInitParameters struct {

	// The ID of the Environment that the Peering belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PeeringEnvironmentObservation struct {

	// The ID of the Environment that the Peering belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PeeringEnvironmentParameters struct {

	// The ID of the Environment that the Peering belongs to, for example, env-abc123.
	// The unique identifier for the environment.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type PeeringGCPInitParameters struct {

	// The Import Custom Routes option enables connectivity to a Confluent Cloud cluster in Google Cloud from customer premise or other clouds, such as AWS and Azure, through a customer VPC that is peered with Confluent Cloud in the same region. Defaults to false. Learn more about considerations / limitations of the Import Custom Routes option here.
	// Enable customer route import. Defaults to `false`.
	ImportCustomRoutes *bool `json:"importCustomRoutes,omitempty" tf:"import_custom_routes,omitempty"`

	// The GCP Project ID. You can find your Google Cloud Project ID under Project ID section of your Google Cloud Console dashboard.
	// The name of the GCP project.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The VPC network name that you're peering to Confluent Cloud. You can find your VPC network name under VPC Networks section of your Google Cloud Console.
	// The name of the GCP VPC network to peer with.
	VPCNetwork *string `json:"vpcNetwork,omitempty" tf:"vpc_network,omitempty"`
}

type PeeringGCPObservation struct {

	// The Import Custom Routes option enables connectivity to a Confluent Cloud cluster in Google Cloud from customer premise or other clouds, such as AWS and Azure, through a customer VPC that is peered with Confluent Cloud in the same region. Defaults to false. Learn more about considerations / limitations of the Import Custom Routes option here.
	// Enable customer route import. Defaults to `false`.
	ImportCustomRoutes *bool `json:"importCustomRoutes,omitempty" tf:"import_custom_routes,omitempty"`

	// The GCP Project ID. You can find your Google Cloud Project ID under Project ID section of your Google Cloud Console dashboard.
	// The name of the GCP project.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The VPC network name that you're peering to Confluent Cloud. You can find your VPC network name under VPC Networks section of your Google Cloud Console.
	// The name of the GCP VPC network to peer with.
	VPCNetwork *string `json:"vpcNetwork,omitempty" tf:"vpc_network,omitempty"`
}

type PeeringGCPParameters struct {

	// The Import Custom Routes option enables connectivity to a Confluent Cloud cluster in Google Cloud from customer premise or other clouds, such as AWS and Azure, through a customer VPC that is peered with Confluent Cloud in the same region. Defaults to false. Learn more about considerations / limitations of the Import Custom Routes option here.
	// Enable customer route import. Defaults to `false`.
	// +kubebuilder:validation:Optional
	ImportCustomRoutes *bool `json:"importCustomRoutes,omitempty" tf:"import_custom_routes,omitempty"`

	// The GCP Project ID. You can find your Google Cloud Project ID under Project ID section of your Google Cloud Console dashboard.
	// The name of the GCP project.
	// +kubebuilder:validation:Optional
	Project *string `json:"project" tf:"project,omitempty"`

	// The VPC network name that you're peering to Confluent Cloud. You can find your VPC network name under VPC Networks section of your Google Cloud Console.
	// The name of the GCP VPC network to peer with.
	// +kubebuilder:validation:Optional
	VPCNetwork *string `json:"vpcNetwork" tf:"vpc_network,omitempty"`
}

type PeeringInitParameters struct {

	// The AWS-specific Peering details if available. It supports the following:
	Aws []PeeringAwsInitParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// The Azure-specific Peering details if available. It supports the following:
	Azure []PeeringAzureInitParameters `json:"azure,omitempty" tf:"azure,omitempty"`

	// The name of the Peering.
	// The name of the Peering.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []PeeringEnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// The Azure-specific Peering details if available. It supports the following:
	GCP []PeeringGCPInitParameters `json:"gcp,omitempty" tf:"gcp,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	Network []PeeringNetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`
}

type PeeringNetworkInitParameters struct {

	// The ID of the Environment that the Peering belongs to, for example, env-abc123.
	// The unique identifier for the network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PeeringNetworkObservation struct {

	// The ID of the Environment that the Peering belongs to, for example, env-abc123.
	// The unique identifier for the network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PeeringNetworkParameters struct {

	// The ID of the Environment that the Peering belongs to, for example, env-abc123.
	// The unique identifier for the network.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type PeeringObservation struct {

	// The AWS-specific Peering details if available. It supports the following:
	Aws []PeeringAwsObservation `json:"aws,omitempty" tf:"aws,omitempty"`

	// The Azure-specific Peering details if available. It supports the following:
	Azure []PeeringAzureObservation `json:"azure,omitempty" tf:"azure,omitempty"`

	// The name of the Peering.
	// The name of the Peering.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []PeeringEnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// The Azure-specific Peering details if available. It supports the following:
	GCP []PeeringGCPObservation `json:"gcp,omitempty" tf:"gcp,omitempty"`

	// The ID of the Environment that the Peering belongs to, for example, env-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	Network []PeeringNetworkObservation `json:"network,omitempty" tf:"network,omitempty"`
}

type PeeringParameters struct {

	// The AWS-specific Peering details if available. It supports the following:
	// +kubebuilder:validation:Optional
	Aws []PeeringAwsParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// The Azure-specific Peering details if available. It supports the following:
	// +kubebuilder:validation:Optional
	Azure []PeeringAzureParameters `json:"azure,omitempty" tf:"azure,omitempty"`

	// The name of the Peering.
	// The name of the Peering.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	// +kubebuilder:validation:Optional
	Environment []PeeringEnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// The Azure-specific Peering details if available. It supports the following:
	// +kubebuilder:validation:Optional
	GCP []PeeringGCPParameters `json:"gcp,omitempty" tf:"gcp,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	// +kubebuilder:validation:Optional
	Network []PeeringNetworkParameters `json:"network,omitempty" tf:"network,omitempty"`
}

// PeeringSpec defines the desired state of Peering
type PeeringSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PeeringParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PeeringInitParameters `json:"initProvider,omitempty"`
}

// PeeringStatus defines the observed state of Peering.
type PeeringStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PeeringObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Peering is the Schema for the Peerings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,confluent}
type Peering struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	Spec   PeeringSpec   `json:"spec"`
	Status PeeringStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PeeringList contains a list of Peerings
type PeeringList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Peering `json:"items"`
}

// Repository type metadata.
var (
	Peering_Kind             = "Peering"
	Peering_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Peering_Kind}.String()
	Peering_KindAPIVersion   = Peering_Kind + "." + CRDGroupVersion.String()
	Peering_GroupVersionKind = CRDGroupVersion.WithKind(Peering_Kind)
)

func init() {
	SchemeBuilder.Register(&Peering{}, &PeeringList{})
}
