apiVersion: schema.confluent.crossplane.io/v1alpha1
kind: BusinessMetadata
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/businessmetadata
  labels:
    testing.upbound.io/example-name: pii
  name: pii
spec:
  forProvider:
    attributeDefinition:
    - name: team
    - name: email
    credentials:
    - keySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      secretSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    description: PII metadata
    name: PII
    restEndpoint: ${data.confluent_schema_registry_cluster.essentials.rest_endpoint}
    schemaRegistryCluster:
    - id: ${data.confluent_schema_registry_cluster.essentials.id}
