apiVersion: schema.confluent.crossplane.io/v1alpha1
kind: SubjectConfig
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/subjectconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    compatibilityGroup: abc.cg.version
    compatibilityLevel: BACKWARD
    credentials:
    - keySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      secretSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    restEndpoint: ${data.confluent_schema_registry_cluster.essentials.rest_endpoint}
    schemaRegistryCluster:
    - id: ${confluent_schema_registry_region.essentials.id}
