apiVersion: schema.confluent.crossplane.io/v1alpha1
kind: TagBinding
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/tagbinding
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    credentials:
    - keySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      secretSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    entityName: ${var.schema_registry_id}:${var.kafka_id}:${data.confluent_kafka_topic.main.topic_name}
    entityType: kafka_topic
    restEndpoint: ${data.confluent_schema_registry_cluster.essentials.rest_endpoint}
    schemaRegistryCluster:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: confluent_schema_registry_cluster
    tagName: PII
