// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/michielvha/upjet-provider-confluent/apis/cluster/confluent/v1alpha1"
	v1alpha1custom "github.com/michielvha/upjet-provider-confluent/apis/cluster/custom/v1alpha1"
	v1alpha1dns "github.com/michielvha/upjet-provider-confluent/apis/cluster/dns/v1alpha1"
	v1alpha1environment "github.com/michielvha/upjet-provider-confluent/apis/cluster/environment/v1alpha1"
	v1alpha1flink "github.com/michielvha/upjet-provider-confluent/apis/cluster/flink/v1alpha1"
	v1alpha1iam "github.com/michielvha/upjet-provider-confluent/apis/cluster/iam/v1alpha1"
	v1alpha1kafka "github.com/michielvha/upjet-provider-confluent/apis/cluster/kafka/v1alpha1"
	v1alpha1ksql "github.com/michielvha/upjet-provider-confluent/apis/cluster/ksql/v1alpha1"
	v1alpha1network "github.com/michielvha/upjet-provider-confluent/apis/cluster/network/v1alpha1"
	v1alpha1private "github.com/michielvha/upjet-provider-confluent/apis/cluster/private/v1alpha1"
	v1alpha1schema "github.com/michielvha/upjet-provider-confluent/apis/cluster/schema/v1alpha1"
	v1alpha1transit "github.com/michielvha/upjet-provider-confluent/apis/cluster/transit/v1alpha1"
	v1alpha1cluster "github.com/michielvha/upjet-provider-confluent/apis/cluster/v1alpha1"
	v1beta1 "github.com/michielvha/upjet-provider-confluent/apis/cluster/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1custom.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1environment.SchemeBuilder.AddToScheme,
		v1alpha1flink.SchemeBuilder.AddToScheme,
		v1alpha1iam.SchemeBuilder.AddToScheme,
		v1alpha1kafka.SchemeBuilder.AddToScheme,
		v1alpha1ksql.SchemeBuilder.AddToScheme,
		v1alpha1network.SchemeBuilder.AddToScheme,
		v1alpha1private.SchemeBuilder.AddToScheme,
		v1alpha1schema.SchemeBuilder.AddToScheme,
		v1alpha1transit.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
