// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EnvironmentInitParameters struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EnvironmentObservation struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the environment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EnvironmentParameters struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the environment.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type LinkEndpointInitParameters struct {

	// The description of the Network Link Endpoint.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the Network Link Endpoint.
	// The display name of the Network Link Endpoint.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []EnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	Network []NetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// supports the following:
	NetworkLinkService []NetworkLinkServiceInitParameters `json:"networkLinkService,omitempty" tf:"network_link_service,omitempty"`
}

type LinkEndpointObservation struct {

	// The description of the Network Link Endpoint.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the Network Link Endpoint.
	// The display name of the Network Link Endpoint.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	Environment []EnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	Network []NetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// supports the following:
	NetworkLinkService []NetworkLinkServiceObservation `json:"networkLinkService,omitempty" tf:"network_link_service,omitempty"`

	// The Confluent Resource Name of the Network Link Endpoint.
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`
}

type LinkEndpointParameters struct {

	// The description of the Network Link Endpoint.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the Network Link Endpoint.
	// The display name of the Network Link Endpoint.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// supports the following:
	// Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
	// +kubebuilder:validation:Optional
	Environment []EnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// supports the following:
	// Network represents a network (VPC) in Confluent Cloud. All Networks exist within Confluent-managed cloud provider accounts.
	// +kubebuilder:validation:Optional
	Network []NetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	NetworkLinkService []NetworkLinkServiceParameters `json:"networkLinkService,omitempty" tf:"network_link_service,omitempty"`
}

type NetworkInitParameters struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworkLinkServiceInitParameters struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the Network Link Endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworkLinkServiceObservation struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the Network Link Endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworkLinkServiceParameters struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the Network Link Endpoint.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type NetworkObservation struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworkParameters struct {

	// The ID of the Network that the Network Link Endpoint belongs to, for example, n-abc123.
	// The unique identifier for the network.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

// LinkEndpointSpec defines the desired state of LinkEndpoint
type LinkEndpointSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LinkEndpointParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LinkEndpointInitParameters `json:"initProvider,omitempty"`
}

// LinkEndpointStatus defines the observed state of LinkEndpoint.
type LinkEndpointStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LinkEndpointObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LinkEndpoint is the Schema for the LinkEndpoints API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,confluent}
type LinkEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkLinkService) || (has(self.initProvider) && has(self.initProvider.networkLinkService))",message="spec.forProvider.networkLinkService is a required parameter"
	Spec   LinkEndpointSpec   `json:"spec"`
	Status LinkEndpointStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LinkEndpointList contains a list of LinkEndpoints
type LinkEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LinkEndpoint `json:"items"`
}

// Repository type metadata.
var (
	LinkEndpoint_Kind             = "LinkEndpoint"
	LinkEndpoint_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LinkEndpoint_Kind}.String()
	LinkEndpoint_KindAPIVersion   = LinkEndpoint_Kind + "." + CRDGroupVersion.String()
	LinkEndpoint_GroupVersionKind = CRDGroupVersion.WithKind(LinkEndpoint_Kind)
)

func init() {
	SchemeBuilder.Register(&LinkEndpoint{}, &LinkEndpointList{})
}
