// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ACLCredentialsInitParameters struct {

	// The Kafka API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Kafka API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type ACLCredentialsObservation struct {
}

type ACLCredentialsParameters struct {

	// The Kafka API Key.
	// The Cluster API Key for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Kafka API Secret.
	// The Cluster API Secret for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type ACLInitParameters struct {

	// supports the following:
	// The Cluster API Credentials.
	Credentials []ACLCredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// supports the following:
	KafkaCluster []KafkaClusterInitParameters `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// The REST endpoint of the Kafka cluster, for example, https://pkc-00000.us-central1.gcp.confluent.cloud:443.
	// The REST endpoint of the Kafka cluster (e.g., `https://pkc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`
}

type ACLObservation struct {

	// supports the following:
	// The Cluster API Credentials.
	Credentials []ACLCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The host for the ACL. Should be set to * for Confluent Cloud.
	// The host for the ACL.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// The ID of the Kafka cluster, for example, lkc-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// supports the following:
	KafkaCluster []KafkaClusterObservation `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// The operation type for the ACL. Accepted values are: ALL, READ, WRITE, CREATE, DELETE, ALTER, DESCRIBE, CLUSTER_ACTION, DESCRIBE_CONFIGS, ALTER_CONFIGS, and IDEMPOTENT_WRITE.  See Authorization using ACLs to find mappings of (resource_type, operation) to one or more Kafka APIs or request types.
	// The operation type for the ACL.
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// The pattern type for the ACL. Accepted values are: LITERAL and PREFIXED.
	// The pattern type for the ACL.
	PatternType *string `json:"patternType,omitempty" tf:"pattern_type,omitempty"`

	// The permission for the ACL. Accepted values are: DENY and ALLOW.
	// The permission for the ACL.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// The principal for the ACL.
	// The principal for the ACL.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The resource name for the ACL. Must be kafka-cluster if resource_type equals to CLUSTER.
	// The resource name for the ACL.
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`

	// The type of the resource. Accepted values are: TOPIC, GROUP, CLUSTER, TRANSACTIONAL_ID, DELEGATION_TOKEN. See Authorization using ACLs to find definitions of resource types and mappings of (resource_type, operation) to one or more Kafka APIs or request types.
	// The type of the resource.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The REST endpoint of the Kafka cluster, for example, https://pkc-00000.us-central1.gcp.confluent.cloud:443.
	// The REST endpoint of the Kafka cluster (e.g., `https://pkc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`
}

type ACLParameters struct {

	// supports the following:
	// The Cluster API Credentials.
	// +kubebuilder:validation:Optional
	Credentials []ACLCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The host for the ACL. Should be set to * for Confluent Cloud.
	// The host for the ACL.
	// +kubebuilder:validation:Required
	Host *string `json:"host" tf:"host,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	KafkaCluster []KafkaClusterParameters `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// The operation type for the ACL. Accepted values are: ALL, READ, WRITE, CREATE, DELETE, ALTER, DESCRIBE, CLUSTER_ACTION, DESCRIBE_CONFIGS, ALTER_CONFIGS, and IDEMPOTENT_WRITE.  See Authorization using ACLs to find mappings of (resource_type, operation) to one or more Kafka APIs or request types.
	// The operation type for the ACL.
	// +kubebuilder:validation:Required
	Operation *string `json:"operation" tf:"operation,omitempty"`

	// The pattern type for the ACL. Accepted values are: LITERAL and PREFIXED.
	// The pattern type for the ACL.
	// +kubebuilder:validation:Required
	PatternType *string `json:"patternType" tf:"pattern_type,omitempty"`

	// The permission for the ACL. Accepted values are: DENY and ALLOW.
	// The permission for the ACL.
	// +kubebuilder:validation:Required
	Permission *string `json:"permission" tf:"permission,omitempty"`

	// The principal for the ACL.
	// The principal for the ACL.
	// +kubebuilder:validation:Required
	Principal *string `json:"principal" tf:"principal,omitempty"`

	// The resource name for the ACL. Must be kafka-cluster if resource_type equals to CLUSTER.
	// The resource name for the ACL.
	// +kubebuilder:validation:Required
	ResourceName *string `json:"resourceName" tf:"resource_name,omitempty"`

	// The type of the resource. Accepted values are: TOPIC, GROUP, CLUSTER, TRANSACTIONAL_ID, DELEGATION_TOKEN. See Authorization using ACLs to find definitions of resource types and mappings of (resource_type, operation) to one or more Kafka APIs or request types.
	// The type of the resource.
	// +kubebuilder:validation:Required
	ResourceType *string `json:"resourceType" tf:"resource_type,omitempty"`

	// The REST endpoint of the Kafka cluster, for example, https://pkc-00000.us-central1.gcp.confluent.cloud:443.
	// The REST endpoint of the Kafka cluster (e.g., `https://pkc-00000.us-central1.gcp.confluent.cloud:443`).
	// +kubebuilder:validation:Optional
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`
}

type KafkaClusterInitParameters struct {

	// The ID of the Kafka cluster, for example, lkc-abc123.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	// +crossplane:generate:reference:type=github.com/michielvha/upjet-provider-confluent/apis/cluster/kafka/v1alpha1.Cluster
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Cluster in kafka to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.NamespacedReference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Cluster in kafka to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.NamespacedSelector `json:"idSelector,omitempty" tf:"-"`
}

type KafkaClusterObservation struct {

	// The ID of the Kafka cluster, for example, lkc-abc123.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type KafkaClusterParameters struct {

	// The ID of the Kafka cluster, for example, lkc-abc123.
	// The Kafka cluster ID (e.g., `lkc-12345`).
	// +crossplane:generate:reference:type=github.com/michielvha/upjet-provider-confluent/apis/cluster/kafka/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Cluster in kafka to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.NamespacedReference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Cluster in kafka to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.NamespacedSelector `json:"idSelector,omitempty" tf:"-"`
}

// ACLSpec defines the desired state of ACL
type ACLSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ACLParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ACLInitParameters `json:"initProvider,omitempty"`
}

// ACLStatus defines the observed state of ACL.
type ACLStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ACLObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ACL is the Schema for the ACLs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,confluent}
type ACL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ACLSpec   `json:"spec"`
	Status            ACLStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ACLList contains a list of ACLs
type ACLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ACL `json:"items"`
}

// Repository type metadata.
var (
	ACL_Kind             = "ACL"
	ACL_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ACL_Kind}.String()
	ACL_KindAPIVersion   = ACL_Kind + "." + CRDGroupVersion.String()
	ACL_GroupVersionKind = CRDGroupVersion.WithKind(ACL_Kind)
)

func init() {
	SchemeBuilder.Register(&ACL{}, &ACLList{})
}
