// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha11 "github.com/michielvha/upjet-provider-confluent/apis/cluster/environment/v1alpha1"
	v1alpha1 "github.com/michielvha/upjet-provider-confluent/apis/cluster/kafka/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ACL.
func (mg *ACL) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.KafkaCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KafkaCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.KafkaCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.KafkaCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterList{},
				Managed: &v1alpha1.Cluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.KafkaCluster[i3].ID")
		}
		mg.Spec.ForProvider.KafkaCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.KafkaCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.KafkaCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KafkaCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.KafkaCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.KafkaCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterList{},
				Managed: &v1alpha1.Cluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.KafkaCluster[i3].ID")
		}
		mg.Spec.InitProvider.KafkaCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.KafkaCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this ClientQuota.
func (mg *ClientQuota) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.KafkaCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KafkaCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.KafkaCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.KafkaCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterList{},
				Managed: &v1alpha1.Cluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.KafkaCluster[i3].ID")
		}
		mg.Spec.ForProvider.KafkaCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.KafkaCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.KafkaCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KafkaCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.KafkaCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.KafkaCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterList{},
				Managed: &v1alpha1.Cluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.KafkaCluster[i3].ID")
		}
		mg.Spec.InitProvider.KafkaCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.KafkaCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Cluster.
func (mg *Cluster) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Environment); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Environment[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Environment[i3].IDRef,
			Selector:     mg.Spec.ForProvider.Environment[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha11.EnvironmentList{},
				Managed: &v1alpha11.Environment{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Environment[i3].ID")
		}
		mg.Spec.ForProvider.Environment[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Environment[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Environment); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Environment[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Environment[i3].IDRef,
			Selector:     mg.Spec.InitProvider.Environment[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha11.EnvironmentList{},
				Managed: &v1alpha11.Environment{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Environment[i3].ID")
		}
		mg.Spec.InitProvider.Environment[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Environment[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this ClusterConfig.
func (mg *ClusterConfig) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.KafkaCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KafkaCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.KafkaCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.KafkaCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterList{},
				Managed: &v1alpha1.Cluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.KafkaCluster[i3].ID")
		}
		mg.Spec.ForProvider.KafkaCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.KafkaCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.KafkaCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KafkaCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.KafkaCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.KafkaCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterList{},
				Managed: &v1alpha1.Cluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.KafkaCluster[i3].ID")
		}
		mg.Spec.InitProvider.KafkaCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.KafkaCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this MirrorTopic.
func (mg *MirrorTopic) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.ClusterLink); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterLink[i3].LinkName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ClusterLink[i3].LinkNameRef,
			Selector:     mg.Spec.ForProvider.ClusterLink[i3].LinkNameSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterLinkList{},
				Managed: &v1alpha1.ClusterLink{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ClusterLink[i3].LinkName")
		}
		mg.Spec.ForProvider.ClusterLink[i3].LinkName = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ClusterLink[i3].LinkNameRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ClusterLink); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterLink[i3].LinkName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ClusterLink[i3].LinkNameRef,
			Selector:     mg.Spec.InitProvider.ClusterLink[i3].LinkNameSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterLinkList{},
				Managed: &v1alpha1.ClusterLink{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ClusterLink[i3].LinkName")
		}
		mg.Spec.InitProvider.ClusterLink[i3].LinkName = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ClusterLink[i3].LinkNameRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Topic.
func (mg *Topic) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.KafkaCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KafkaCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.KafkaCluster[i3].IDRef,
			Selector:     mg.Spec.ForProvider.KafkaCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterList{},
				Managed: &v1alpha1.Cluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.KafkaCluster[i3].ID")
		}
		mg.Spec.ForProvider.KafkaCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.KafkaCluster[i3].IDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.KafkaCluster); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KafkaCluster[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.KafkaCluster[i3].IDRef,
			Selector:     mg.Spec.InitProvider.KafkaCluster[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.ClusterList{},
				Managed: &v1alpha1.Cluster{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.KafkaCluster[i3].ID")
		}
		mg.Spec.InitProvider.KafkaCluster[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.KafkaCluster[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}
