// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type KafkaClusterCredentialsInitParameters struct {

	// The Kafka API Key.
	// The Kafka API Key for your Confluent Cloud cluster.
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Kafka API Secret.
	// The Kafka API Secret for your Confluent Cloud cluster.
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type KafkaClusterCredentialsObservation struct {
}

type KafkaClusterCredentialsParameters struct {

	// The Kafka API Key.
	// The Kafka API Key for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	KeySecretRef v1.LocalSecretKeySelector `json:"keySecretRef" tf:"-"`

	// The Kafka API Secret.
	// The Kafka API Secret for your Confluent Cloud cluster.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type MirrorTopicClusterLinkInitParameters struct {

	// The name of the cluster link to attach to the mirror topic, for example, my-cluster-link.
	// The name of the Cluster Link.
	// +crossplane:generate:reference:type=github.com/michielvha/upjet-provider-confluent/apis/cluster/kafka/v1alpha1.ClusterLink
	LinkName *string `json:"linkName,omitempty" tf:"link_name,omitempty"`

	// Reference to a ClusterLink in kafka to populate linkName.
	// +kubebuilder:validation:Optional
	LinkNameRef *v1.NamespacedReference `json:"linkNameRef,omitempty" tf:"-"`

	// Selector for a ClusterLink in kafka to populate linkName.
	// +kubebuilder:validation:Optional
	LinkNameSelector *v1.NamespacedSelector `json:"linkNameSelector,omitempty" tf:"-"`
}

type MirrorTopicClusterLinkObservation struct {

	// The name of the cluster link to attach to the mirror topic, for example, my-cluster-link.
	// The name of the Cluster Link.
	LinkName *string `json:"linkName,omitempty" tf:"link_name,omitempty"`
}

type MirrorTopicClusterLinkParameters struct {

	// The name of the cluster link to attach to the mirror topic, for example, my-cluster-link.
	// The name of the Cluster Link.
	// +crossplane:generate:reference:type=github.com/michielvha/upjet-provider-confluent/apis/cluster/kafka/v1alpha1.ClusterLink
	// +kubebuilder:validation:Optional
	LinkName *string `json:"linkName,omitempty" tf:"link_name,omitempty"`

	// Reference to a ClusterLink in kafka to populate linkName.
	// +kubebuilder:validation:Optional
	LinkNameRef *v1.NamespacedReference `json:"linkNameRef,omitempty" tf:"-"`

	// Selector for a ClusterLink in kafka to populate linkName.
	// +kubebuilder:validation:Optional
	LinkNameSelector *v1.NamespacedSelector `json:"linkNameSelector,omitempty" tf:"-"`
}

type MirrorTopicInitParameters struct {

	// supports the following:
	ClusterLink []MirrorTopicClusterLinkInitParameters `json:"clusterLink,omitempty" tf:"cluster_link,omitempty"`

	// supports the following:
	KafkaCluster []MirrorTopicKafkaClusterInitParameters `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// The name of the mirror topic. Only required when there is a prefix configured on the cluster link. For example, when <prefix> is configured for the cluster link, the mirror topic name has to be of the format <prefix><source_topic_name>.
	// Name of the topic to be mirrored over the Kafka Mirror Topic, i.e. the source topic's name. Only required when there is a prefix configured on the link.
	MirrorTopicName *string `json:"mirrorTopicName,omitempty" tf:"mirror_topic_name,omitempty"`

	// supports the following:
	SourceKafkaTopic []SourceKafkaTopicInitParameters `json:"sourceKafkaTopic,omitempty" tf:"source_kafka_topic,omitempty"`

	// > "PAUSED"), resuming ("PAUSED" -> "ACTIVE"), promoting, and failing over a mirror topic is supported via an update operation. Defaults to "ACTIVE".
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type MirrorTopicKafkaClusterInitParameters struct {

	// supports the following:
	// The Kafka API Credentials.
	Credentials []KafkaClusterCredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The ID of the destination Kafka cluster, for example, lkc-abc123.
	// The unique identifier for the referred Kafka cluster.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The REST endpoint of the destination Kafka cluster, for example, https://pkc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Kafka cluster (e.g., `https://pkc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`
}

type MirrorTopicKafkaClusterObservation struct {

	// supports the following:
	// The Kafka API Credentials.
	Credentials []KafkaClusterCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The ID of the destination Kafka cluster, for example, lkc-abc123.
	// The unique identifier for the referred Kafka cluster.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The REST endpoint of the destination Kafka cluster, for example, https://pkc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Kafka cluster (e.g., `https://pkc-00000.us-central1.gcp.confluent.cloud:443`).
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`
}

type MirrorTopicKafkaClusterParameters struct {

	// supports the following:
	// The Kafka API Credentials.
	// +kubebuilder:validation:Optional
	Credentials []KafkaClusterCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// The ID of the destination Kafka cluster, for example, lkc-abc123.
	// The unique identifier for the referred Kafka cluster.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The REST endpoint of the destination Kafka cluster, for example, https://pkc-00000.us-central1.gcp.confluent.cloud:443).
	// The REST endpoint of the Kafka cluster (e.g., `https://pkc-00000.us-central1.gcp.confluent.cloud:443`).
	// +kubebuilder:validation:Optional
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`
}

type MirrorTopicObservation struct {

	// supports the following:
	ClusterLink []MirrorTopicClusterLinkObservation `json:"clusterLink,omitempty" tf:"cluster_link,omitempty"`

	// The ID of the destination Kafka cluster, for example, lkc-abc123.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// supports the following:
	KafkaCluster []MirrorTopicKafkaClusterObservation `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// The name of the mirror topic. Only required when there is a prefix configured on the cluster link. For example, when <prefix> is configured for the cluster link, the mirror topic name has to be of the format <prefix><source_topic_name>.
	// Name of the topic to be mirrored over the Kafka Mirror Topic, i.e. the source topic's name. Only required when there is a prefix configured on the link.
	MirrorTopicName *string `json:"mirrorTopicName,omitempty" tf:"mirror_topic_name,omitempty"`

	// supports the following:
	SourceKafkaTopic []SourceKafkaTopicObservation `json:"sourceKafkaTopic,omitempty" tf:"source_kafka_topic,omitempty"`

	// > "PAUSED"), resuming ("PAUSED" -> "ACTIVE"), promoting, and failing over a mirror topic is supported via an update operation. Defaults to "ACTIVE".
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type MirrorTopicParameters struct {

	// supports the following:
	// +kubebuilder:validation:Optional
	ClusterLink []MirrorTopicClusterLinkParameters `json:"clusterLink,omitempty" tf:"cluster_link,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	KafkaCluster []MirrorTopicKafkaClusterParameters `json:"kafkaCluster,omitempty" tf:"kafka_cluster,omitempty"`

	// The name of the mirror topic. Only required when there is a prefix configured on the cluster link. For example, when <prefix> is configured for the cluster link, the mirror topic name has to be of the format <prefix><source_topic_name>.
	// Name of the topic to be mirrored over the Kafka Mirror Topic, i.e. the source topic's name. Only required when there is a prefix configured on the link.
	// +kubebuilder:validation:Optional
	MirrorTopicName *string `json:"mirrorTopicName,omitempty" tf:"mirror_topic_name,omitempty"`

	// supports the following:
	// +kubebuilder:validation:Optional
	SourceKafkaTopic []SourceKafkaTopicParameters `json:"sourceKafkaTopic,omitempty" tf:"source_kafka_topic,omitempty"`

	// > "PAUSED"), resuming ("PAUSED" -> "ACTIVE"), promoting, and failing over a mirror topic is supported via an update operation. Defaults to "ACTIVE".
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type SourceKafkaTopicInitParameters struct {

	// The name of the topic on the source cluster to be mirrored over the cluster link, for example, orders. A topic with the exact same name must exist on the source cluster, and no topic with this name should exist on the destination cluster.
	// The name of the Source Kafka topic.
	TopicName *string `json:"topicName,omitempty" tf:"topic_name,omitempty"`
}

type SourceKafkaTopicObservation struct {

	// The name of the topic on the source cluster to be mirrored over the cluster link, for example, orders. A topic with the exact same name must exist on the source cluster, and no topic with this name should exist on the destination cluster.
	// The name of the Source Kafka topic.
	TopicName *string `json:"topicName,omitempty" tf:"topic_name,omitempty"`
}

type SourceKafkaTopicParameters struct {

	// The name of the topic on the source cluster to be mirrored over the cluster link, for example, orders. A topic with the exact same name must exist on the source cluster, and no topic with this name should exist on the destination cluster.
	// The name of the Source Kafka topic.
	// +kubebuilder:validation:Optional
	TopicName *string `json:"topicName" tf:"topic_name,omitempty"`
}

// MirrorTopicSpec defines the desired state of MirrorTopic
type MirrorTopicSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MirrorTopicParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MirrorTopicInitParameters `json:"initProvider,omitempty"`
}

// MirrorTopicStatus defines the observed state of MirrorTopic.
type MirrorTopicStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MirrorTopicObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MirrorTopic is the Schema for the MirrorTopics API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,confluent}
type MirrorTopic struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterLink) || (has(self.initProvider) && has(self.initProvider.clusterLink))",message="spec.forProvider.clusterLink is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.kafkaCluster) || (has(self.initProvider) && has(self.initProvider.kafkaCluster))",message="spec.forProvider.kafkaCluster is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sourceKafkaTopic) || (has(self.initProvider) && has(self.initProvider.sourceKafkaTopic))",message="spec.forProvider.sourceKafkaTopic is a required parameter"
	Spec   MirrorTopicSpec   `json:"spec"`
	Status MirrorTopicStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MirrorTopicList contains a list of MirrorTopics
type MirrorTopicList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MirrorTopic `json:"items"`
}

// Repository type metadata.
var (
	MirrorTopic_Kind             = "MirrorTopic"
	MirrorTopic_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MirrorTopic_Kind}.String()
	MirrorTopic_KindAPIVersion   = MirrorTopic_Kind + "." + CRDGroupVersion.String()
	MirrorTopic_GroupVersionKind = CRDGroupVersion.WithKind(MirrorTopic_Kind)
)

func init() {
	SchemeBuilder.Register(&MirrorTopic{}, &MirrorTopicList{})
}
